In [25]:
import pandas as pd
import numpy as np
from sklearn import linear_model

In [9]:
df = pd.read_csv('nta_housing311.csv')
df.head()

/opt/rh/anaconda/root/envs/PUI2016_Python3/lib/python3.5/site-packages/IPython/core/interactiveshell.py:2717: DtypeWarning: Columns (19,42,43,45,49,52,55,60,64,65,66,68,69,70,71,75,76,77,78,79,80,82,83,84,85,87,88,90,92,93,94,97,98,101,107,111,112,113,114,115,124,157,160,161,163,164,166,172) have mixed types. Specify dtype option on import or set low_memory=False.
  interactivity=interactivity, compiler=compiler, result=result)


Unnamed: 0  Unnamed: 0.1  unique_key         created_date  \
0           0             0    21722467  2011-10-24 08:58:00   
1          20            20    21723669  2011-10-24 14:39:00   
2          80            81    21727928  2011-10-25 00:28:00   
3          90            91    21728908  2011-10-25 23:38:00   
4         116           117    21729998  2011-10-25 23:34:00   

           closed_date agency                             agency_name  \
0  2011-10-26 01:45:00    dep  department of environmental protection   
1  2011-10-26 06:45:00    dep  department of environmental protection   
2  2011-10-26 20:00:00    dep  department of environmental protection   
3  2011-10-31 20:00:00    dep  department of environmental protection   
4  2011-11-01 01:45:00    dep  department of environmental protection   

  complaint_type                                    descriptor location_type  \
0          noise  noise: construction before/after hours (nm1)           NaN   
1          noise           noise: construction equipment (nc1)           NaN   
2          noise           noise: construction equipment (nc1)           NaN   
3          noise                   noise: jack hammering (nc2)           NaN   
4          noise                   noise: jack hammering (nc2)           NaN   

    ...        No rent paid  \
0   ...               408.0   
1   ...               408.0   
2   ...               408.0   
3   ...               408.0   
4   ...               408.0   

  Occupied units paying rent (excl. units where GRAPI can't be computed)  \
0                                              14520                       
1                                              14520                       
2                                              14520                       
3                                              14520                       
4                                              14520                       

     Less than 15.0 percent    15.0 to 19.9 percent.1  \
0                    3308.0                    1847.0   
1                    3308.0                    1847.0   
2                    3308.0                    1847.0   
3                    3308.0                    1847.0   
4                    3308.0                    1847.0   

     20.0 to 24.9 percent.2    25.0 to 29.9 percent.2  \
0                    1803.0                    1755.0   
1                    1803.0                    1755.0   
2                    1803.0                    1755.0   
3                    1803.0                    1755.0   
4                    1803.0                    1755.0   

     30.0 to 34.9 percent.2    35.0 percent or more.2    Not computed.2  \
0                    1285.0                      4522             669.0   
1                    1285.0                      4522             669.0   
2                    1285.0                      4522             669.0   
3                    1285.0                      4522             669.0   
4                    1285.0                      4522             669.0   

  NTA_code  
0     MN25  
1     MN25  
2     MN25  
3     MN25  
4     MN25  

[5 rows x 175 columns]

In [10]:
#df.columns = df.columns.str.strip()

In [11]:
cols = ['Unnamed: 0','Unnamed: 0.1','created_date','closed_date','agency','agency_name','complaint_type','descriptor','location_type','street_name','cross_street_1','cross_street_2','intersection_street_1','intersection_street_2','address_type','city','landmark','facility_type','status','due_date','resolution_description','resolution_action_updated_date']

In [12]:
df.drop(cols, axis = 1, inplace = True)

In [14]:
df_pivot = pd.pivot_table(df, index = df.NTA_code)

In [15]:
df_pivot.columns = df_pivot.columns.str.strip()

In [16]:
df_pivot.head()

$1,000 to $1,499  $1,000,000 or more  $1,500 to $1,999  \
NTA_code                                                           
BK28                 512.0               590.0             635.0   
BK31                 998.0              1242.0            1132.0   
BK33                 250.0              1974.0             268.0   
BK35                 325.0               161.0             789.0   
BK42                 558.0              1113.0             515.0   

          $100 to $199  $100,000 to $149,999  $150,000 to $199,999  \
NTA_code                                                             
BK28              42.0                 182.0                 170.0   
BK31             174.0                 334.0                 334.0   
BK33              35.0                  30.0                  64.0   
BK35              20.0                  40.0                  43.0   
BK42             110.0                 215.0                 483.0   

          $2,000 or more  $200 to $299  $200 to $299.1  $200,000 to $299,999  \
NTA_code                                                                       
BK28              3527.0         128.0           326.0                 310.0   
BK31              4613.0         194.0           470.0                1583.0   
BK33              2360.0          13.0          1133.0                  36.0   
BK35              2746.0           0.0          1454.0                 248.0   
BK42              2786.0         108.0           622.0                 759.0   

                     ...              county_fip  incident_zip  index_right  \
NTA_code             ...                                                      
BK28                 ...                    47.0  11211.583857         65.0   
BK31                 ...                    47.0  11210.603343        123.0   
BK33                 ...                    47.0  11226.392078        168.0   
BK35                 ...                    47.0  11221.132747         28.0   
BK42                 ...                    47.0  11224.211930        102.0   

           latitude  longitude    shape_area    shape_leng    unique_key  \
NTA_code                                                                   
BK28      40.612330 -73.995556  4.667057e+07  37137.439681  3.182655e+07   
BK31      40.626742 -74.028912  6.712000e+07  44410.045677  3.194218e+07   
BK33      40.680880 -74.000872  4.460138e+07  60820.884104  3.243372e+07   
BK35      40.688531 -73.932669  3.140694e+07  28239.080558  3.361654e+07   
BK42      40.642212 -73.960755  4.525481e+07  38737.853081  3.244929e+07   

          x_coordinate_(state_plane)  y_coordinate_(state_plane)  
NTA_code                                                          
BK28                    9.854838e+05               162364.821877  
BK31                    9.762244e+05               167616.812776  
BK33                    9.840081e+05               187339.411803  
BK35                    1.002923e+06               190133.979620  
BK42                    9.951414e+05               173253.830073  

[5 rows x 97 columns]

In [17]:
df_pivot.columns

Index(['$1,000 to $1,499', '$1,000,000 or more', '$1,500 to $1,999',
       '$100 to $199', '$100,000 to $149,999', '$150,000 to $199,999',
       '$2,000 or more', '$200 to $299', '$200 to $299.1',
       '$200,000 to $299,999', '$300 to $399', '$300 to $499',
       '$300,000 to $499,999', '$400 or more', '$50,000 to $99,999',
       '$500 to $699', '$500,000 to $999,999', '$700 to $999', '$750 to $999',
       '1-unit, attached', '1-unit, detached', '10 to 19 units',
       '10.0 to 14.9 percent', '15.0 to 19.9 percent',
       '15.0 to 19.9 percent.1', '2 rooms', '2 units', '2 vehicles available',
       '20.0 to 24.9 percent', '20.0 to 24.9 percent.1',
       '20.0 to 24.9 percent.2', '25.0 to 29.9 percent',
       '25.0 to 29.9 percent.1', '25.0 to 29.9 percent.2',
       '3 or more vehicles available', '30.0 to 34.9 percent',
       '30.0 to 34.9 percent.1', '30.0 to 34.9 percent.2',
       '35.0 percent or more', '35.0 percent or more.1', '5 or more bedrooms',
       '5 to 9 un

In [23]:
df_pivot.reset_index(level = 0, inplace = True)
df_pivot.head()

NTA_code  $1,000 to $1,499  $1,000,000 or more  $1,500 to $1,999  \
0     BK28             512.0               590.0             635.0   
1     BK31             998.0              1242.0            1132.0   
2     BK33             250.0              1974.0             268.0   
3     BK35             325.0               161.0             789.0   
4     BK42             558.0              1113.0             515.0   

   $100 to $199  $100,000 to $149,999  $150,000 to $199,999  $2,000 or more  \
0          42.0                 182.0                 170.0          3527.0   
1         174.0                 334.0                 334.0          4613.0   
2          35.0                  30.0                  64.0          2360.0   
3          20.0                  40.0                  43.0          2746.0   
4         110.0                 215.0                 483.0          2786.0   

   $200 to $299  $200 to $299.1             ...              county_fip  \
0         128.0           326.0             ...                    47.0   
1         194.0           470.0             ...                    47.0   
2          13.0          1133.0             ...                    47.0   
3           0.0          1454.0             ...                    47.0   
4         108.0           622.0             ...                    47.0   

   incident_zip  index_right   latitude  longitude    shape_area  \
0  11211.583857         65.0  40.612330 -73.995556  4.667057e+07   
1  11210.603343        123.0  40.626742 -74.028912  6.712000e+07   
2  11226.392078        168.0  40.680880 -74.000872  4.460138e+07   
3  11221.132747         28.0  40.688531 -73.932669  3.140694e+07   
4  11224.211930        102.0  40.642212 -73.960755  4.525481e+07   

     shape_leng    unique_key  x_coordinate_(state_plane)  \
0  37137.439681  3.182655e+07                9.854838e+05   
1  44410.045677  3.194218e+07                9.762244e+05   
2  60820.884104  3.243372e+07                9.840081e+05   
3  28239.080558  3.361654e+07                1.002923e+06   
4  38737.853081  3.244929e+07                9.951414e+05   

   y_coordinate_(state_plane)  
0               162364.821877  
1               167616.812776  
2               187339.411803  
3               190133.979620  
4               173253.830073  

[5 rows x 98 columns]

In [30]:
for col in df_pivot.columns[1:-12]:
    df_pivot[col] = df_pivot[col].astype('float')

In [39]:
x = pd.factorize(df_pivot.NTA_code)
df_pivot.NTA_code = x[0]

In [63]:
for alpha in range(1,1000):
    Lasso=linear_model.Lasso(fit_intercept=True, alpha=alpha, max_iter=10000)
    Lasso.fit(df_pivot.iloc[:,1:-12],df_pivot.NTA_code)

/opt/rh/anaconda/root/envs/PUI2016_Python3/lib/python3.5/site-packages/sklearn/linear_model/coordinate_descent.py:491: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations. Fitting data with very small alpha may cause precision problems.
  ConvergenceWarning)


In [64]:
print(Lasso.sparse_coef_)

  (0, 12)	0.0025119905307020144
  (0, 16)	-0.002876839582490109
  (0, 18)	-0.0005183477434098121
  (0, 25)	0.0025666176010600565
  (0, 41)	-0.000409872758996417
  (0, 47)	0.002307068992819103
  (0, 48)	0.00016670481432675676
  (0, 50)	0.0006810125121577817
  (0, 56)	-0.0006337102972683238


In [65]:
Lasso.coef_

array([ 0.        , -0.        ,  0.        ,  0.        ,  0.        ,
        0.        , -0.        ,  0.        , -0.        ,  0.        ,
        0.        , -0.        ,  0.00251199,  0.        , -0.        ,
       -0.        , -0.00287684, -0.        , -0.00051835,  0.        ,
        0.        ,  0.        ,  0.        ,  0.        , -0.        ,
        0.00256662, -0.        ,  0.        , -0.        ,  0.        ,
       -0.        , -0.        ,  0.        , -0.        ,  0.        ,
       -0.        ,  0.        , -0.        , -0.        ,  0.        ,
       -0.        , -0.00040987,  0.        ,  0.        , -0.        ,
       -0.        , -0.        ,  0.00230707,  0.0001667 ,  0.        ,
        0.00068101,  0.        ,  0.        , -0.        , -0.        ,
        0.        , -0.00063371,  0.        ,  0.        , -0.        ,
       -0.        ,  0.        , -0.        , -0.        , -0.        ,
        0.        , -0.        , -0.        ,  0.        ,  0.  

In [66]:
x

(array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
        17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
        34, 35, 36, 37]),
 Index(['BK28', 'BK31', 'BK33', 'BK35', 'BK42', 'BK63', 'BK64', 'BK69', 'BK72',
        'BK73', 'BK75', 'BK78', 'BK88', 'BX09', 'BX13', 'BX22', 'BX31', 'BX43',
        'BX63', 'MN11', 'MN12', 'MN13', 'MN17', 'MN19', 'MN22', 'MN23', 'MN24',
        'MN25', 'MN28', 'MN32', 'MN35', 'MN36', 'QN01', 'QN17', 'QN22', 'QN28',
        'QN70', 'SI25'],
       dtype='object'))

In [67]:
for alpha in range(1,1000):
    Ridge=linear_model.Ridge(fit_intercept=True, alpha=alpha, max_iter=10000)
    Ridge.fit(df_pivot.iloc[:,1:-12],df_pivot.NTA_code)

Ridge.coef_

array([-7.24740812e-04, -8.29163745e-05,  1.46702899e-03,  2.45134542e-04,
        9.16049307e-04, -8.09038758e-04, -9.34078119e-04,  1.12175022e-03,
       -4.36942795e-03,  1.86631760e-04, -1.78435269e-03,  9.80079219e-04,
        5.42371598e-03,  2.89222260e-03,  1.99376644e-03, -3.40496465e-03,
       -6.41231627e-03,  5.71611036e-04,  2.81799323e-03,  2.05308444e-03,
        2.39746668e-03,  3.86782264e-03,  8.09683980e-04,  4.71260567e-03,
        8.22671347e-03,  6.77788794e-03, -1.16477301e-03,  3.91402913e-04,
        3.48526596e-03,  2.58784403e-03, -7.34629187e-03, -4.24203725e-03,
        1.23605057e-03,  2.97243422e-04,  8.39715850e-03, -9.33205162e-03,
       -7.35503325e-04, -5.32222164e-03,  1.82702774e-03, -7.82477277e-03,
        4.57680518e-03,  1.60263198e-04,  1.43828412e-03,  4.39583889e-03,
       -6.51326061e-03, -9.83722399e-04, -4.22970506e-03, -2.61523371e-03,
        2.65829286e-03, -1.73375987e-03,  1.94957207e-03,  1.76226873e-03,
        3.93511736e-03, -