In [1]:
import pandas as pd
import numpy as np
from sklearn import linear_model

In [2]:
df = pd.read_csv('nta_socio311.csv')
df.head()

/opt/rh/anaconda/root/envs/PUI2016_Python3/lib/python3.5/site-packages/IPython/core/interactiveshell.py:2717: DtypeWarning: Columns (19) have mixed types. Specify dtype option on import or set low_memory=False.
  interactivity=interactivity, compiler=compiler, result=result)


Unnamed: 0  Unnamed: 0.1  unique_key         created_date  \
0           0             0    21722467  2011-10-24 08:58:00   
1          20            20    21723669  2011-10-24 14:39:00   
2          80            81    21727928  2011-10-25 00:28:00   
3          90            91    21728908  2011-10-25 23:38:00   
4         116           117    21729998  2011-10-25 23:34:00   

           closed_date agency                             agency_name  \
0  2011-10-26 01:45:00    dep  department of environmental protection   
1  2011-10-26 06:45:00    dep  department of environmental protection   
2  2011-10-26 20:00:00    dep  department of environmental protection   
3  2011-10-31 20:00:00    dep  department of environmental protection   
4  2011-11-01 01:45:00    dep  department of environmental protection   

  complaint_type                                    descriptor location_type  \
0          noise  noise: construction before/after hours (nm1)           NaN   
1          noise           noise: construction equipment (nc1)           NaN   
2          noise           noise: construction equipment (nc1)           NaN   
3          noise                   noise: jack hammering (nc2)           NaN   
4          noise                   noise: jack hammering (nc2)           NaN   

    ...     Russian Scotch-Irish Scottish Slovak Subsaharan African Swiss  \
0   ...      2506.0         77.0    556.0   53.0              251.0  73.0   
1   ...      2506.0         77.0    556.0   53.0              251.0  73.0   
2   ...      2506.0         77.0    556.0   53.0              251.0  73.0   
3   ...      2506.0         77.0    556.0   53.0              251.0  73.0   
4   ...      2506.0         77.0    556.0   53.0              251.0  73.0   

  Ukrainian  Welsh West Indian (excluding Hispanic origin groups) NTA_code  
0     269.0  249.0                                          278.0     MN25  
1     269.0  249.0                                          278.0     MN25  
2     269.0  249.0                                          278.0     MN25  
3     269.0  249.0                                          278.0     MN25  
4     269.0  249.0                                          278.0     MN25  

[5 rows x 176 columns]

In [3]:
cols = ['Unnamed: 0','Unnamed: 0.1','created_date','closed_date','agency','agency_name','complaint_type','descriptor','location_type','street_name','cross_street_1','cross_street_2','intersection_street_1','intersection_street_2','address_type','city','landmark','facility_type','status','due_date','resolution_description','resolution_action_updated_date']

In [4]:
df.drop(cols, axis = 1, inplace = True)

In [5]:
df_pivot = pd.pivot_table(df, index = df.NTA_code)

In [6]:
df_pivot.columns = df_pivot.columns.str.strip()

In [7]:
df_pivot.head()

9th to 12th grade, no diploma  Abroad  Africa  American   Arab  \
NTA_code                                                                   
BK88                             7026.0   786.0   385.0    4747.0  787.0   
BX31                             2091.0   212.0   542.0     271.0  363.0   
BX43                             3418.0   641.0   601.0     660.0  299.0   
BX63                             3893.0   590.0  2503.0     273.0  221.0   
MN11                             3144.0   366.0  2226.0    1130.0  207.0   

             Asia  Asian and Pacific Islander languages  Associate's degree  \
NTA_code                                                                      
BK88      13213.0                                9526.0              2167.0   
BX31       1833.0                                1253.0              1465.0   
BX43       2888.0                                 874.0              1374.0   
BX63        804.0                                 355.0              1325.0   
MN11       1459.0                                 987.0              1645.0   

          Average family size  Average household size  \
NTA_code                                                
BK88                      4.3                     3.7   
BX31                      3.9                     3.3   
BX43                      3.7                     2.9   
BX63                      3.7                     3.1   
MN11                      3.4                     2.5   

                     ...              county_fip  incident_zip  index_right  \
NTA_code             ...                                                      
BK88                 ...                    47.0  11215.530529          0.0   
BX31                 ...                     5.0  10468.997022         32.0   
BX43                 ...                     5.0  10466.858915        138.0   
BX63                 ...                     5.0  10451.809289        176.0   
MN11                 ...                    61.0  10026.368934        193.0   

           latitude  longitude    shape_area    shape_leng    unique_key  \
NTA_code                                                                   
BK88      40.632629 -73.989570  5.400502e+07  39247.228074  3.268229e+07   
BX31      40.866226 -73.849977  3.169304e+07  25467.117344  3.235874e+07   
BX43      40.877765 -73.878027  1.572493e+07  22150.308055  3.216894e+07   
BX63      40.834604 -73.919575  1.937982e+07  28499.044489  3.322374e+07   
MN11      40.803701 -73.951680  1.443930e+07  16621.023753  3.331913e+07   

          x_coordinate_(state_plane)  y_coordinate_(state_plane)  
NTA_code                                                          
BK88                    9.871451e+05               169760.395559  
BX31                    1.025745e+06               254902.563772  
BX43                    1.017980e+06               259094.568560  
BX63                    1.006505e+06               243356.104349  
MN11                    9.976274e+05               232090.521974  

[5 rows x 143 columns]

In [8]:
df_pivot.columns

Index(['9th to 12th grade, no diploma', 'Abroad', 'Africa', 'American', 'Arab',
       'Asia', 'Asian and Pacific Islander languages', 'Associate's degree',
       'Average family size', 'Average household size',
       ...
       'county_fip', 'incident_zip', 'index_right', 'latitude', 'longitude',
       'shape_area', 'shape_leng', 'unique_key', 'x_coordinate_(state_plane)',
       'y_coordinate_(state_plane)'],
      dtype='object', length=143)

In [9]:
df_pivot.reset_index(level = 0, inplace = True)
df_pivot.head()

NTA_code  9th to 12th grade, no diploma  Abroad  Africa  American   Arab  \
0     BK88                         7026.0   786.0   385.0    4747.0  787.0   
1     BX31                         2091.0   212.0   542.0     271.0  363.0   
2     BX43                         3418.0   641.0   601.0     660.0  299.0   
3     BX63                         3893.0   590.0  2503.0     273.0  221.0   
4     MN11                         3144.0   366.0  2226.0    1130.0  207.0   

      Asia  Asian and Pacific Islander languages  Associate's degree  \
0  13213.0                                9526.0              2167.0   
1   1833.0                                1253.0              1465.0   
2   2888.0                                 874.0              1374.0   
3    804.0                                 355.0              1325.0   
4   1459.0                                 987.0              1645.0   

   Average family size             ...              county_fip  incident_zip  \
0                  4.3             ...                    47.0  11215.530529   
1                  3.9             ...                     5.0  10468.997022   
2                  3.7             ...                     5.0  10466.858915   
3                  3.7             ...                     5.0  10451.809289   
4                  3.4             ...                    61.0  10026.368934   

   index_right   latitude  longitude    shape_area    shape_leng  \
0          0.0  40.632629 -73.989570  5.400502e+07  39247.228074   
1         32.0  40.866226 -73.849977  3.169304e+07  25467.117344   
2        138.0  40.877765 -73.878027  1.572493e+07  22150.308055   
3        176.0  40.834604 -73.919575  1.937982e+07  28499.044489   
4        193.0  40.803701 -73.951680  1.443930e+07  16621.023753   

     unique_key  x_coordinate_(state_plane)  y_coordinate_(state_plane)  
0  3.268229e+07                9.871451e+05               169760.395559  
1  3.235874e+07                1.025745e+06               254902.563772  
2  3.216894e+07                1.017980e+06               259094.568560  
3  3.322374e+07                1.006505e+06               243356.104349  
4  3.331913e+07                9.976274e+05               232090.521974  

[5 rows x 144 columns]

In [13]:
for col in df_pivot.columns[1:-12]:
    df_pivot[col] = df_pivot[col].astype('float')

In [14]:
x = pd.factorize(df_pivot.NTA_code)
df_pivot.NTA_code = x[0]

In [15]:
for alpha in range(1,1000):
    Lasso=linear_model.Lasso(fit_intercept=True, alpha=alpha, max_iter=10000)
    Lasso.fit(df_pivot.iloc[:,1:-12],df_pivot.NTA_code)

/opt/rh/anaconda/root/envs/PUI2016_Python3/lib/python3.5/site-packages/sklearn/linear_model/coordinate_descent.py:491: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations. Fitting data with very small alpha may cause precision problems.
  ConvergenceWarning)


In [16]:
print(Lasso.sparse_coef_)

  (0, 6)	0.0004889057035124549
  (0, 19)	0.00022250485293324817
  (0, 27)	0.0002835709894090419
  (0, 31)	0.00018607066044044063
  (0, 34)	0.0001844768755791664
  (0, 46)	-0.0001379259837986375
  (0, 70)	-0.000365370732012777
  (0, 114)	-0.00011065943853807533


In [17]:
Lasso.coef_

array([ 0.        , -0.        , -0.        ,  0.        , -0.        ,
        0.        ,  0.00048891,  0.        , -0.        , -0.        ,
        0.        , -0.        , -0.        ,  0.        , -0.        ,
       -0.        ,  0.        ,  0.        ,  0.        ,  0.0002225 ,
        0.        , -0.        , -0.        , -0.        , -0.        ,
       -0.        , -0.        ,  0.00028357,  0.        , -0.        ,
       -0.        ,  0.00018607, -0.        ,  0.        ,  0.00018448,
        0.        ,  0.        ,  0.        ,  0.        , -0.        ,
       -0.        , -0.        ,  0.        ,  0.        , -0.        ,
       -0.        , -0.00013793, -0.        , -0.        , -0.        ,
        0.        ,  0.        , -0.        ,  0.        , -0.        ,
       -0.        , -0.        ,  0.        ,  0.        ,  0.        ,
        0.        , -0.        ,  0.        , -0.        , -0.        ,
       -0.        ,  0.        ,  0.        ,  0.        , -0.  

In [18]:
x

(array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14]),
 Index(['BK88', 'BX31', 'BX43', 'BX63', 'MN11', 'MN12', 'MN13', 'MN19', 'MN23',
        'MN24', 'MN25', 'MN28', 'MN32', 'QN01', 'QN28'],
       dtype='object'))

In [20]:
for alpha in range(1,1000):
    Ridge=linear_model.Ridge(fit_intercept=True, alpha=alpha, max_iter=10000)
    Ridge.fit(df_pivot.iloc[:,1:-12],df_pivot.NTA_code)

In [21]:
Ridge.coef_

array([ 1.31858900e-04,  2.76231088e-05,  1.00825234e-04,  2.87440440e-04,
       -5.35870830e-05, -4.28273101e-06,  3.16301790e-04,  8.49986997e-06,
       -5.94788366e-08,  9.52461751e-09,  1.29676749e-04,  2.68071042e-05,
       -1.46365177e-04, -1.06203742e-04,  4.37180579e-06,  1.48204130e-04,
        8.45736818e-07,  4.67695648e-06,  3.46665253e-04,  4.16140388e-04,
        1.57433896e-04, -9.63013880e-05, -6.31620165e-05, -5.49028016e-05,
        2.11849820e-05,  5.08811520e-05, -1.61230967e-04,  2.94165130e-04,
        1.90324158e-05, -5.84785681e-05,  7.77468841e-06,  1.58450406e-04,
       -2.94307411e-04,  1.12134805e-04,  2.89371873e-04,  9.99718382e-05,
        9.99718382e-05,  9.99718382e-05,  9.99718382e-05, -6.43854948e-05,
       -1.49918356e-05, -1.57486246e-05,  2.28109196e-05,  2.88556664e-05,
       -1.84358107e-05, -7.44333743e-05, -5.06105255e-04, -3.42316175e-05,
        9.26962031e-05, -1.37364673e-04,  1.17351741e-04,  1.67958621e-04,
       -6.62216708e-05,  